title: Michael W. Henson
description: A PhD candidate in Dr. Cameron Thrash's lab at LSU
show_downloads: true
email: Hensonmw at gmail dot come
twitter_username: Hensonmw_08
github_username: Hensonmw
google_analytics: "UA-116920343-1"
url: "http://hensonmw.github.io"
theme: jekyll-theme-cayman
markdown: kramdown
